# Generated by Django 3.1.3 on 2020-12-04 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='time_created',
        ),
    ]
