# Generated by Django 3.1.1 on 2020-12-21 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_listings_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='category',
            field=models.CharField(choices=[(None, 'Choose Category'), ('Toys', 'Toys'), ('Electronics', 'Electronics')], default=None, max_length=64),
        ),
    ]
